download_url: https://galaxy.ansible.com/download/devsec-hardening-7.15.0.tar.gz
format_version: 1.0.0
name: hardening
namespace: devsec
server: https://galaxy.ansible.com/api/
signatures: []
version: 7.15.0
version_url: https://galaxy.ansible.com/api/v2/collections/devsec/hardening/versions/7.15.0/
